baseURL = 'https://lionsos.org/'
languageCode = 'en-au'
title = 'LionsOS [draft docs]'
theme = 'hugo-book'

[markup.goldmark.renderer]
unsafe = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
  BookSection = 'docs'
